// 明らかなミスで例外が出ない例
// console.log(3 + [])

// let obj = {}
// console.log(obj.foo)

// function a(b) {
//   return console.log(b/2)
// }

// a("z")